### ISSUE TITLE
사전미션 제출 실패

### ISSUE THREAD

**Issue by WooHey-P** [JunBeum-Cho/wanted-pre-onboarding-challenge-BE-task-may#1]
프리온보딩 백엔드 챌린지 5월 의 사전미션 제출 클릭 시 콘솔에

ycatch.js:150     POST https://forms.reform.app/forms/.../submissions 500

이라고 출력되면서 흰 화면만 출력되네요.. 혹시 제출이 된 건지 궁금합니다.

**Comment by JunBeum-Cho** [comment]
왜 500에러가 났는지 잘 모르겠지만..
dk***lnd@naver.com 이메일로 잘 들어왔습니다 :)

**Comment by WooHey-P** [comment]
다행이네요 :) 감사합니다.
